### PR TITLE
Made powder variants more in line with their source items

### PR DESCRIPTION
**Pull request by DoubtfulFanboy**
Powder variants were not properly colour matched to their source items.

Additionally, organic dyes were giving unique textures to fall in line with vanilla gameplay.

Unchanged powder textures as there is no available source textures:

- cobalt powder
- confusing powder
- tin powder
- ardite powder
- withering powder

### CODE REVIEW

**Comment by Rover656** [comment]
Looking good, tagged and I'll have a close look at the textures when I'm able :)

**Review by justliliandev — CHANGES_REQUESTED** [review]
quartz_powder has a spelling mistake (quarts_powder)
I really like the new powder textures

**Comment by Rover656** [comment]
After the naming change could you also add permission to use your textures as CC0 into the doc/license folder? Thanks!

**Comment by Rover656** [comment]
I'm happy to merge if we're all good with these textures.

**Comment by justliliandev** [comment]
I'm fine with that too

**Pull request merged**
